
services:
  redis:
    image: redis:7.2.8
    container_name: railway-redis-1
    ports:
      - "6379:6379"
    command: redis-server --requirepass sgP7uvhkNQvn9bV57hRQiHQSkU2MU46A
    volumes:
      - redis_data:/data

  tracker:
    build: .
    container_name: railway-tracker-1
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PWD=sgP7uvhkNQvn9bV57hRQiHQSkU2MU46A
    volumes:
      - .:/app
    command: python tracker.py

volumes:
  redis_data:
